# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genere', models.CharField(max_length=55)),
            ],
        ),
        migrations.AlterField(
            model_name='music',
            name='genere',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='music_app.Genere'),
        ),
    ]
