# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0002_auto_20161029_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='rating',
        ),
    ]
