# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 10:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_app', '0004_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='music',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='music_track', to='music_app.Music'),
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ManyToManyField(default='', to=settings.AUTH_USER_MODEL),
        ),
    ]
