# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0006_auto_20161028_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_track', to='music_app.Music'),
        ),
    ]
