# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0008_auto_20161028_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='music',
        ),
        migrations.AddField(
            model_name='music',
            name='ratings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music_app.Rating'),
        ),
    ]
